services:
  - docker:dind

stages:
  - test
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

test:cargo:
  stage: test
  image: $CI_REGISTRY_IMAGE
  tags:
    - docker
  script:
    - rustc --version && cargo --version # Print version info for debugging
    - export CARGO_INCREMENTAL=0
    - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off"
    - cargo test --verbose $CARGO_OPTIONS

# benchmark:cargo:
#   stage: test
# image: $CI_REGISTRY_IMAGE
#   tags:
#     - docker
#   script:
#     - cargo bench +nightly -v -- -Z unstable-options --format=json > bench_results.json
#     # again vaild json..
#     - ./format_json.sh bench_results.json
#   cache:
#     key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
#     paths:
#       - target/debug/deps
#       - target/release/deps
#     policy: pull
#   artifacts:
#     paths:
#       - bench_results.json
#     expire_in: 30 days

coverage:cargo:
  stage: test
  image: $CI_REGISTRY_IMAGE
  tags:
    - docker
  script:
    - cargo cov build && cargo cov test && cargo cov report
  artifacts:
    paths:
      - target/cov/report

doc:cargo:
  stage: build
  image: $CI_REGISTRY_IMAGE
  tags:
    - docker
  script:
    - cargo doc --no-deps
  artifacts:
    paths:
      - target/doc

build:cargo:
  stage: build
  image: $CI_REGISTRY_IMAGE
  tags:
    - docker
  script:
    - cargo build --release
    - strip target/release/superrustendo
    - strip target/release/snesdbg
    - strip target/release/snesdis
  artifacts:
    paths:
      - target/release/{superrustendo,snesdbg,snesdis}
    untracked: false
    expire_in: 30 days

docker:
  tags:
    - docker
  image: docker
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master
# TODO: Build release image containing only alpine and build binaries

pages:
  tags:
    - docker
  stage: deploy
  image: $CI_REGISTRY_IMAGE
  dependencies:
    - coverage:cargo
    - doc:cargo
  script:
    - mkdir public
    - mv target/cov/report public/cov
    - mv target/doc public/doc
    - mv pages.html public/index.html
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
